name: Update Mailbox List

on:
  schedule:
    - cron: '0 0 1 * *'  # 每月1号午夜运行
  workflow_dispatch:      # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run script
      env:
        SMARTY_API_CREDENTIALS: ${{ secrets.SMARTY_API_CREDENTIALS }}
      run: python -m src.main
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add result/mailboxes.csv
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update mailbox list [skip ci]" && git push) 